version: "3"
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する

  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: "demo" # 初期データベース
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf # my.cnf をマウント
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306

volumes:
  mysql_data:
